### ISSUE TITLE
Update morphological dictionary link to one compatible with libvoikko 4.x

### ISSUE THREAD

**Issue by anko** [fergusq/tampio#2]
I'm using libvoikko 4.1.1, so the link to the morphological dictionary file (format version 2) given in the readme didn't work for me. [This one](https://www.puimula.org/htp/testing/voikko-snapshot-v5/dict-morpho.zip) (in format version 5) did. Time to update the link?

**Comment by anko** [comment]
Related question: will you do [that PPCG Finnish independence day challenge](https://codegolf.stackexchange.com/questions/149842/happy-birthday-finland) with this language [too](https://codegolf.stackexchange.com/questions/149842/happy-birthday-finland/149847#149847)? I'd rather leave it to you (since I've written no Haskell for 5 years), but I feel it must happen. :smile:

**Comment by fergusq** [comment]
I would love to answer that challenge, but unfortunately this language lacks I/O capabilities to print colored text or to detect the date. A new version is in development, but I don't have time to make it for the independence day.

**Comment by fergusq** [comment]
Hmm, dictionary format 5 doesn't seem to work with my libvoikko (version 3.8). I'll put it to the readme but have both links there in case either one doesn't work. Do you change the `LANGUAGE` to `fi-mor-morpho` from `fi-x-morpho` in the code?

**Comment by anko** [comment]
I'm using the code as-is. 

[The page where I found the v5 format file](https://www.puimula.org/htp/testing/voikko-snapshot-v5/) says—

> Sanastoformaatti 5 toimii libvoikon version 4.0 ja uudempien kanssa.

My distro's package manager provides libvoikko 4.1.1, so I went with it. I think linking both formats from the readme is a good idea.

Hyvää itsenäisyyspäivää! :finland:
